// Dados mockados
export const mockProfessionals = [
  {
    id: "1",
    name: "João Silva",
    profession: "Eletricista",
    location: "São Paulo, SP",
    distance: "3.5 km",
    rating: 4.8,
    reviewCount: 124,
    verified: true,
    image: "",
    tags: ["Instalação", "Manutenção", "Residencial", "Comercial"],
    responseTime: "1 hora",
  },
  {
    id: "2",
    name: "Maria Oliveira",
    profession: "Pintora",
    location: "São Paulo, SP",
    distance: "5.2 km",
    rating: 4.5,
    reviewCount: 93,
    verified: true,
    image: "",
    tags: ["Interior", "Exterior", "Textura", "Residencial"],
    responseTime: "30 minutos",
  },
  {
    id: "3",
    name: "Pedro Santos",
    profession: "Pedreiro",
    location: "São Paulo, SP",
    distance: "2.8 km",
    rating: 4.7,
    reviewCount: 215,
    verified: false,
    image: "",
    tags: ["Construção", "Reforma", "Alvenaria", "Fundação"],
    responseTime: "2 horas",
  },
  {
    id: "4",
    name: "Ana Costa",
    profession: "Encanadora",
    location: "São Paulo, SP",
    distance: "4.7 km",
    rating: 4.9,
    reviewCount: 87,
    verified: true,
    image: "",
    tags: ["Encanamento", "Vazamentos", "Instalação", "Manutenção"],
    responseTime: "1 hora",
  },
  {
    id: "5",
    name: "Carlos Ferreira",
    profession: "Marceneiro",
    location: "São Paulo, SP",
    distance: "7.2 km",
    rating: 4.6,
    reviewCount: 152,
    verified: true,
    image: "",
    tags: ["Móveis", "Restauração", "Personalização", "Madeira Maciça"],
    responseTime: "3 horas",
  },
];
