export const allRequests = [
  {
    id: 2,
    titulo: "Conserto de Vazamento",
    descricao: "Vazamento identificado atrás do vaso sanitário.",
    categoria: "Hidráulica",
    urgencia: "Alta",
    status: "Finalizado",
    localizacao: "São Paulo, SP",
    criadoEm: "01/05/2025",
    prazo: "03/05/2025",
    cliente: { nome: "Carlos Lima" },
    imagens: [
      "https://picsum.photos/seed/4/700/400",
      "https://picsum.photos/seed/5/700/400",
    ],
  },
  {
    id: 3,
    titulo: "Troca de Luminárias",
    descricao: "Trocar 3 luminárias antigas por novas de LED no escritório.",
    categoria: "Elétrica",
    urgencia: "Normal",
    status: "Em Execução",
    localizacao: "Campinas, SP",
    criadoEm: "05/05/2025",
    prazo: "12/05/2025",
    cliente: { nome: "Fernanda Souza" },
    imagens: [
      "https://picsum.photos/seed/6/700/400",
      "https://picsum.photos/seed/7/700/400",
    ],
  },
  {
    id: 4,
    titulo: "Pintura de Quarto",
    descricao: "Pintar 1 quarto de casal com tinta branca lavável.",
    categoria: "Pintura",
    urgencia: "Baixa",
    status: "Cancelado",
    localizacao: "Santo André, SP",
    criadoEm: "08/05/2025",
    prazo: "20/05/2025",
    cliente: { nome: "João Pereira" },
    imagens: ["https://picsum.photos/seed/8/700/400"],
  },
  {
    id: 5,
    titulo: "Instalação de Câmeras de Segurança",
    descricao: "Instalar 4 câmeras com DVR em casa térrea.",
    categoria: "Segurança",
    urgencia: "Alta",
    status: "Aceito",
    localizacao: "Guarulhos, SP",
    criadoEm: "06/05/2025",
    prazo: "13/05/2025",
    cliente: { nome: "Luciana Ramos" },
    imagens: [
      "https://picsum.photos/seed/9/700/400",
      "https://picsum.photos/seed/10/700/400",
    ],
  },
];
